services:
  app:
    build:
      context: .
      args:
        # The Git commit and the jj change ID of the code. The README gives the
        # build command.
        CDPP_COMMIT: ${CDPP_COMMIT:-}
        CDPP_CHANGE: ${CDPP_CHANGE:-}
    ports:
      - "8000:8000"
    volumes:
      - data:/data

volumes:
  data:
