services:
  app:
    build:
      context: .
      args:
        # The Git commit of the code. The README gives the build command.
        CDPP_COMMIT: ${CDPP_COMMIT:-}
    ports:
      - "8000:8000"
    volumes:
      - data:/data

volumes:
  data:
