[project]
name = "cdpp"
version = "0.3.0"
description = "Cuneiform Digital Palaeography Project"
readme = "README.md"
authors = [{ name = "Stephan Hügel", email = "urschrei@gmail.com" }]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.13,<0.13"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM", "RUF"]

[tool.pytest.ini_options]
testpaths = ["tests"]
