"""Drop the tablet import timestamp

Revision ID: 4143f0482f76
Revises: 3f9a1c7d52be
Create Date: 2026-09-13 00:32:21.813862

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4143f0482f76"
down_revision = "3f9a1c7d52be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tablet", schema=None) as batch_op:
        batch_op.drop_column("timestamp")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tablet", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "timestamp",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###
