"""Index foreign key columns

Revision ID: c17301121c9c
Revises: ff2824a9b054
Create Date: 2026-09-13 00:21:37.485518

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c17301121c9c"
down_revision = "ff2824a9b054"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cdp", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cdp_cdli_id"), ["cdli_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_cdp_description_id"), ["description_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cdp_oracc_id"), ["oracc_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_cdp_sign_id"), ["sign_id"], unique=False)

    with op.batch_alter_table("city", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_city_locality_id"), ["locality_id"], unique=False
        )

    with op.batch_alter_table("city_site", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_city_site_city_id"), ["city_id"], unique=False
        )

    with op.batch_alter_table("correspondent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_correspondent_non_ruler_id"), ["non_ruler_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_correspondent_ruler_id"), ["ruler_id"], unique=False
        )

    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_instance_column_id"), ["column_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_instance_function_id"), ["function_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_instance_iteration_id"), ["iteration_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_instance_line_id"), ["line_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_instance_sign_id"), ["sign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_instance_surface_id"), ["surface_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_instance_tablet_id"), ["tablet_id"], unique=False
        )

    with op.batch_alter_table("instance_language", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_instance_language_language_id"),
            ["language_id"],
            unique=False,
        )

    with op.batch_alter_table("reign", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reign_city_id"), ["city_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reign_dynasty_id"), ["dynasty_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reign_end_date"), ["end_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reign_period_id"), ["period_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reign_ruler_id"), ["ruler_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reign_start_date"), ["start_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reign_sub_period_id"), ["sub_period_id"], unique=False
        )

    with op.batch_alter_table("ruler_tablet", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ruler_tablet_tablet_id"), ["tablet_id"], unique=False
        )

    with op.batch_alter_table("sub_locality", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sub_locality_locality_id"), ["locality_id"], unique=False
        )

    with op.batch_alter_table("sub_period", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sub_period_period_id"), ["period_id"], unique=False
        )

    with op.batch_alter_table("subperiod_dynasty", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subperiod_dynasty_dynasty_id"), ["dynasty_id"], unique=False
        )

    with op.batch_alter_table("tablet", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tablet_author_id"), ["author_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_city_id"), ["city_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_city_site_id"), ["city_site_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_dynasty_id"), ["dynasty_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_eponym_id"), ["eponym_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_from_id"), ["from_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_function_id"), ["function_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_genre_id"), ["genre_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_language_id"), ["language_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_locality_id"), ["locality_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_medium_id"), ["medium_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_method_id"), ["method_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_origin_city_id"), ["origin_city_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_period_id"), ["period_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_reign_id"), ["reign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_script_type_id"), ["script_type_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_sub_locality_id"), ["sub_locality_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_sub_period_id"), ["sub_period_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tablet_text_vehicle_id"), ["text_vehicle_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tablet_to_id"), ["to_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tablet_year_id"), ["year_id"], unique=False
        )

    with op.batch_alter_table("tablet_correspondent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tablet_correspondent_correspondent_id"),
            ["correspondent_id"],
            unique=False,
        )

    with op.batch_alter_table("year", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_year_eponym_id"), ["eponym_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("year", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_year_eponym_id"))

    with op.batch_alter_table("tablet_correspondent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tablet_correspondent_correspondent_id"))

    with op.batch_alter_table("tablet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tablet_year_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_to_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_text_vehicle_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_sub_period_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_sub_locality_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_script_type_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_reign_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_period_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_origin_city_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_method_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_medium_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_locality_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_language_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_genre_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_function_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_from_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_eponym_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_dynasty_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_city_site_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_city_id"))
        batch_op.drop_index(batch_op.f("ix_tablet_author_id"))

    with op.batch_alter_table("subperiod_dynasty", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subperiod_dynasty_dynasty_id"))

    with op.batch_alter_table("sub_period", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sub_period_period_id"))

    with op.batch_alter_table("sub_locality", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sub_locality_locality_id"))

    with op.batch_alter_table("ruler_tablet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ruler_tablet_tablet_id"))

    with op.batch_alter_table("reign", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reign_sub_period_id"))
        batch_op.drop_index(batch_op.f("ix_reign_start_date"))
        batch_op.drop_index(batch_op.f("ix_reign_ruler_id"))
        batch_op.drop_index(batch_op.f("ix_reign_period_id"))
        batch_op.drop_index(batch_op.f("ix_reign_end_date"))
        batch_op.drop_index(batch_op.f("ix_reign_dynasty_id"))
        batch_op.drop_index(batch_op.f("ix_reign_city_id"))

    with op.batch_alter_table("instance_language", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instance_language_language_id"))

    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instance_tablet_id"))
        batch_op.drop_index(batch_op.f("ix_instance_surface_id"))
        batch_op.drop_index(batch_op.f("ix_instance_sign_id"))
        batch_op.drop_index(batch_op.f("ix_instance_line_id"))
        batch_op.drop_index(batch_op.f("ix_instance_iteration_id"))
        batch_op.drop_index(batch_op.f("ix_instance_function_id"))
        batch_op.drop_index(batch_op.f("ix_instance_column_id"))

    with op.batch_alter_table("correspondent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_correspondent_ruler_id"))
        batch_op.drop_index(batch_op.f("ix_correspondent_non_ruler_id"))

    with op.batch_alter_table("city_site", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_city_site_city_id"))

    with op.batch_alter_table("city", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_city_locality_id"))

    with op.batch_alter_table("cdp", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cdp_sign_id"))
        batch_op.drop_index(batch_op.f("ix_cdp_oracc_id"))
        batch_op.drop_index(batch_op.f("ix_cdp_description_id"))
        batch_op.drop_index(batch_op.f("ix_cdp_cdli_id"))

    # ### end Alembic commands ###
