"""Initial schema

Revision ID: ff2824a9b054
Revises:
Create Date: 2026-09-12 23:24:00.850360

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff2824a9b054"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("name", sa.String(length=75), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_author")),
        sa.UniqueConstraint("name", name=op.f("uq_author_name")),
    )
    op.create_table(
        "cdli",
        sa.Column("sign_ref", sa.String(length=150), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cdli")),
    )
    with op.batch_alter_table("cdli", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cdli_sign_ref"), ["sign_ref"], unique=True)

    op.create_table(
        "column",
        sa.Column("number", sa.String(length=5), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column")),
        sa.UniqueConstraint("number", name=op.f("uq_column_number")),
    )
    op.create_table(
        "description",
        sa.Column("sign_ref", sa.String(length=150), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_description")),
    )
    with op.batch_alter_table("description", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_description_sign_ref"), ["sign_ref"], unique=True
        )

    op.create_table(
        "dynasty",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dynasty")),
        sa.UniqueConstraint("name", name=op.f("uq_dynasty_name")),
    )
    op.create_table(
        "eponym",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eponym")),
        sa.UniqueConstraint("name", name=op.f("uq_eponym_name")),
    )
    op.create_table(
        "function",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_function")),
        sa.UniqueConstraint("name", name=op.f("uq_function_name")),
    )
    op.create_table(
        "genre",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genre")),
        sa.UniqueConstraint("name", name=op.f("uq_genre_name")),
    )
    op.create_table(
        "iteration",
        sa.Column("number", sa.String(length=5), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iteration")),
        sa.UniqueConstraint("number", name=op.f("uq_iteration_number")),
    )
    op.create_table(
        "language",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_language")),
        sa.UniqueConstraint("name", name=op.f("uq_language_name")),
    )
    op.create_table(
        "line",
        sa.Column("number", sa.String(length=5), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_line")),
        sa.UniqueConstraint("number", name=op.f("uq_line_number")),
    )
    op.create_table(
        "locality",
        sa.Column("area", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locality")),
        sa.UniqueConstraint("area", name=op.f("uq_locality_area")),
    )
    op.create_table(
        "medium",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medium")),
        sa.UniqueConstraint("name", name=op.f("uq_medium_name")),
    )
    op.create_table(
        "method",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_method")),
        sa.UniqueConstraint("name", name=op.f("uq_method_name")),
    )
    op.create_table(
        "non_ruler_corresp",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_non_ruler_corresp")),
        sa.UniqueConstraint("name", name=op.f("uq_non_ruler_corresp_name")),
    )
    op.create_table(
        "oracc",
        sa.Column("sign_ref", sa.String(length=150), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oracc")),
    )
    with op.batch_alter_table("oracc", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oracc_sign_ref"), ["sign_ref"], unique=True
        )

    op.create_table(
        "period",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("from_date", sa.String(length=50), nullable=False),
        sa.Column("to_date", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_period")),
        sa.UniqueConstraint("name", name=op.f("uq_period_name")),
    )
    op.create_table(
        "ruler",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ruler")),
        sa.UniqueConstraint("name", name=op.f("uq_ruler_name")),
    )
    op.create_table(
        "script_type",
        sa.Column("script", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_script_type")),
        sa.UniqueConstraint("script", name=op.f("uq_script_type_script")),
    )
    op.create_table(
        "sign",
        sa.Column("sign_ref", sa.String(length=150), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sign")),
    )
    with op.batch_alter_table("sign", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sign_sign_ref"), ["sign_ref"], unique=True)

    op.create_table(
        "surface",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surface")),
        sa.UniqueConstraint("name", name=op.f("uq_surface_name")),
    )
    op.create_table(
        "text_vehicle",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("bm_catalogue", sa.String(length=100), nullable=True),
        sa.Column("cdli", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_text_vehicle")),
        sa.UniqueConstraint("name", name=op.f("uq_text_vehicle_name")),
    )
    op.create_table(
        "cdp",
        sa.Column("sign_id", sa.Integer(), nullable=False),
        sa.Column("description_id", sa.Integer(), nullable=True),
        sa.Column("oracc_id", sa.Integer(), nullable=True),
        sa.Column("cdli_id", sa.Integer(), nullable=True),
        sa.Column("form_name", sa.String(length=5), nullable=True),
        sa.Column("variant_name", sa.String(length=5), nullable=True),
        sa.Column("form_description", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.String(length=50), nullable=True),
        sa.Column("MesZL", sa.String(length=50), nullable=True),
        sa.Column("ELLes", sa.String(length=50), nullable=True),
        sa.Column("ZATU", sa.String(length=50), nullable=True),
        sa.Column("LAK", sa.String(length=50), nullable=True),
        sa.Column("UET_2", sa.String(length=50), nullable=True),
        sa.Column("ARM_XV", sa.String(length=50), nullable=True),
        sa.Column("Hinke", sa.String(length=50), nullable=True),
        sa.Column("Clay_BE_A_14", sa.String(length=50), nullable=True),
        sa.Column("Koenig_AfO_Bei_16", sa.String(length=50), nullable=True),
        sa.Column("Ranke_BE_A_61", sa.String(length=50), nullable=True),
        sa.Column("Schroeder_VS_12", sa.String(length=50), nullable=True),
        sa.Column("Clay_BE_A_10", sa.String(length=50), nullable=True),
        sa.Column("RSP", sa.String(length=50), nullable=True),
        sa.Column("Emar", sa.String(length=50), nullable=True),
        sa.Column("Schroder_VS_15", sa.String(length=50), nullable=True),
        sa.Column("HZL", sa.String(length=50), nullable=True),
        sa.Column("HA", sa.String(length=50), nullable=True),
        sa.Column("aBZL", sa.String(length=50), nullable=True),
        sa.Column("REC", sa.String(length=50), nullable=True),
        sa.Column("Labat", sa.String(length=50), nullable=True),
        sa.Column("KWU", sa.String(length=50), nullable=True),
        sa.Column("Fossey_pp", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cdli_id"],
            ["cdli.id"],
            name=op.f("fk_cdp_cdli_id_cdli"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["description_id"],
            ["description.id"],
            name=op.f("fk_cdp_description_id_description"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["oracc_id"],
            ["oracc.id"],
            name=op.f("fk_cdp_oracc_id_oracc"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sign_id"],
            ["sign.id"],
            name=op.f("fk_cdp_sign_id_sign"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cdp")),
    )
    op.create_table(
        "city",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("locality_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["locality_id"], ["locality.id"], name=op.f("fk_city_locality_id_locality")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_city")),
        sa.UniqueConstraint("name", name=op.f("uq_city_name")),
    )
    op.create_table(
        "correspondent",
        sa.Column("ruler_id", sa.Integer(), nullable=True),
        sa.Column("non_ruler_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["non_ruler_id"],
            ["non_ruler_corresp.id"],
            name=op.f("fk_correspondent_non_ruler_id_non_ruler_corresp"),
        ),
        sa.ForeignKeyConstraint(
            ["ruler_id"], ["ruler.id"], name=op.f("fk_correspondent_ruler_id_ruler")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_correspondent")),
    )
    op.create_table(
        "sub_locality",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("locality_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["locality_id"],
            ["locality.id"],
            name=op.f("fk_sub_locality_locality_id_locality"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sub_locality")),
        sa.UniqueConstraint("name", name=op.f("uq_sub_locality_name")),
    )
    op.create_table(
        "sub_period",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["period_id"], ["period.id"], name=op.f("fk_sub_period_period_id_period")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sub_period")),
        sa.UniqueConstraint("name", name=op.f("uq_sub_period_name")),
    )
    op.create_table(
        "year",
        sa.Column("year", sa.String(length=14), nullable=False),
        sa.Column("eponym_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eponym_id"], ["eponym.id"], name=op.f("fk_year_eponym_id_eponym")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_year")),
        sa.UniqueConstraint("year", name=op.f("uq_year_year")),
    )
    op.create_table(
        "city_site",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"], ["city.id"], name=op.f("fk_city_site_city_id_city")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_city_site")),
        sa.UniqueConstraint("name", name=op.f("uq_city_site_name")),
    )
    op.create_table(
        "reign",
        sa.Column("ruler_id", sa.Integer(), nullable=False),
        sa.Column("rim_ref", sa.String(length=50), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Integer(), nullable=True),
        sa.Column("end_date", sa.Integer(), nullable=True),
        sa.Column("dynasty_id", sa.Integer(), nullable=True),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("sub_period_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"], ["city.id"], name=op.f("fk_reign_city_id_city")
        ),
        sa.ForeignKeyConstraint(
            ["dynasty_id"], ["dynasty.id"], name=op.f("fk_reign_dynasty_id_dynasty")
        ),
        sa.ForeignKeyConstraint(
            ["end_date"], ["year.id"], name=op.f("fk_reign_end_date_year")
        ),
        sa.ForeignKeyConstraint(
            ["period_id"], ["period.id"], name=op.f("fk_reign_period_id_period")
        ),
        sa.ForeignKeyConstraint(
            ["ruler_id"], ["ruler.id"], name=op.f("fk_reign_ruler_id_ruler")
        ),
        sa.ForeignKeyConstraint(
            ["start_date"], ["year.id"], name=op.f("fk_reign_start_date_year")
        ),
        sa.ForeignKeyConstraint(
            ["sub_period_id"],
            ["sub_period.id"],
            name=op.f("fk_reign_sub_period_id_sub_period"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reign")),
    )
    op.create_table(
        "subperiod_dynasty",
        sa.Column("subperiod_id", sa.Integer(), nullable=False),
        sa.Column("dynasty_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dynasty_id"],
            ["dynasty.id"],
            name=op.f("fk_subperiod_dynasty_dynasty_id_dynasty"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subperiod_id"],
            ["sub_period.id"],
            name=op.f("fk_subperiod_dynasty_subperiod_id_sub_period"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "subperiod_id", "dynasty_id", name=op.f("pk_subperiod_dynasty")
        ),
    )
    op.create_table(
        "tablet",
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("museum_number", sa.String(length=75), nullable=False),
        sa.Column("medium_id", sa.Integer(), nullable=False),
        sa.Column("script_type_id", sa.Integer(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("city_site_id", sa.Integer(), nullable=True),
        sa.Column("origin_city_id", sa.Integer(), nullable=True),
        sa.Column("publication", sa.String(length=200), nullable=True),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("sub_period_id", sa.Integer(), nullable=True),
        sa.Column("from_id", sa.Integer(), nullable=True),
        sa.Column("to_id", sa.Integer(), nullable=True),
        sa.Column("language_id", sa.Integer(), nullable=True),
        sa.Column("eponym_id", sa.Integer(), nullable=True),
        sa.Column("year_id", sa.Integer(), nullable=True),
        sa.Column("absolute_month", sa.String(length=10), nullable=True),
        sa.Column("absolute_day", sa.String(length=10), nullable=True),
        sa.Column("ancient_year", sa.String(length=10), nullable=True),
        sa.Column("ancient_month", sa.String(length=10), nullable=True),
        sa.Column("ancient_day", sa.String(length=10), nullable=True),
        sa.Column("dynasty_id", sa.Integer(), nullable=True),
        sa.Column("text_vehicle_id", sa.Integer(), nullable=True),
        sa.Column("locality_id", sa.Integer(), nullable=True),
        sa.Column("sub_locality_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("method_id", sa.Integer(), nullable=True),
        sa.Column("genre_id", sa.Integer(), nullable=True),
        sa.Column("function_id", sa.Integer(), nullable=True),
        sa.Column("reign_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["author.id"], name=op.f("fk_tablet_author_id_author")
        ),
        sa.ForeignKeyConstraint(
            ["city_id"], ["city.id"], name=op.f("fk_tablet_city_id_city")
        ),
        sa.ForeignKeyConstraint(
            ["city_site_id"],
            ["city_site.id"],
            name=op.f("fk_tablet_city_site_id_city_site"),
        ),
        sa.ForeignKeyConstraint(
            ["dynasty_id"], ["dynasty.id"], name=op.f("fk_tablet_dynasty_id_dynasty")
        ),
        sa.ForeignKeyConstraint(
            ["eponym_id"], ["eponym.id"], name=op.f("fk_tablet_eponym_id_eponym")
        ),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["correspondent.id"],
            name=op.f("fk_tablet_from_id_correspondent"),
        ),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["function.id"],
            name=op.f("fk_tablet_function_id_function"),
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"], ["genre.id"], name=op.f("fk_tablet_genre_id_genre")
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
            name=op.f("fk_tablet_language_id_language"),
        ),
        sa.ForeignKeyConstraint(
            ["locality_id"],
            ["locality.id"],
            name=op.f("fk_tablet_locality_id_locality"),
        ),
        sa.ForeignKeyConstraint(
            ["medium_id"], ["medium.id"], name=op.f("fk_tablet_medium_id_medium")
        ),
        sa.ForeignKeyConstraint(
            ["method_id"], ["method.id"], name=op.f("fk_tablet_method_id_method")
        ),
        sa.ForeignKeyConstraint(
            ["origin_city_id"], ["city.id"], name=op.f("fk_tablet_origin_city_id_city")
        ),
        sa.ForeignKeyConstraint(
            ["period_id"], ["period.id"], name=op.f("fk_tablet_period_id_period")
        ),
        sa.ForeignKeyConstraint(
            ["reign_id"], ["reign.id"], name=op.f("fk_tablet_reign_id_reign")
        ),
        sa.ForeignKeyConstraint(
            ["script_type_id"],
            ["script_type.id"],
            name=op.f("fk_tablet_script_type_id_script_type"),
        ),
        sa.ForeignKeyConstraint(
            ["sub_locality_id"],
            ["sub_locality.id"],
            name=op.f("fk_tablet_sub_locality_id_sub_locality"),
        ),
        sa.ForeignKeyConstraint(
            ["sub_period_id"],
            ["sub_period.id"],
            name=op.f("fk_tablet_sub_period_id_sub_period"),
        ),
        sa.ForeignKeyConstraint(
            ["text_vehicle_id"],
            ["text_vehicle.id"],
            name=op.f("fk_tablet_text_vehicle_id_text_vehicle"),
        ),
        sa.ForeignKeyConstraint(
            ["to_id"], ["correspondent.id"], name=op.f("fk_tablet_to_id_correspondent")
        ),
        sa.ForeignKeyConstraint(
            ["year_id"], ["year.id"], name=op.f("fk_tablet_year_id_year")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tablet")),
        sa.UniqueConstraint("museum_number", name=op.f("uq_tablet_museum_number")),
    )
    op.create_table(
        "instance",
        sa.Column("tablet_id", sa.Integer(), nullable=False),
        sa.Column("sign_id", sa.Integer(), nullable=False),
        sa.Column("surface_id", sa.Integer(), nullable=True),
        sa.Column("column_id", sa.Integer(), nullable=True),
        sa.Column("line_id", sa.Integer(), nullable=True),
        sa.Column("function_id", sa.Integer(), nullable=True),
        sa.Column("iteration_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=250), nullable=True),
        sa.Column("jjt_notes", sa.String(length=250), nullable=True),
        sa.Column("filename", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["column_id"], ["column.id"], name=op.f("fk_instance_column_id_column")
        ),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["function.id"],
            name=op.f("fk_instance_function_id_function"),
        ),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["iteration.id"],
            name=op.f("fk_instance_iteration_id_iteration"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["line.id"], name=op.f("fk_instance_line_id_line")
        ),
        sa.ForeignKeyConstraint(
            ["sign_id"],
            ["sign.id"],
            name=op.f("fk_instance_sign_id_sign"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["surface_id"], ["surface.id"], name=op.f("fk_instance_surface_id_surface")
        ),
        sa.ForeignKeyConstraint(
            ["tablet_id"],
            ["tablet.id"],
            name=op.f("fk_instance_tablet_id_tablet"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instance")),
        sa.UniqueConstraint("filename", name=op.f("uq_instance_filename")),
    )
    op.create_table(
        "ruler_tablet",
        sa.Column("ruler_id", sa.Integer(), nullable=False),
        sa.Column("tablet_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ruler_id"],
            ["ruler.id"],
            name=op.f("fk_ruler_tablet_ruler_id_ruler"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tablet_id"],
            ["tablet.id"],
            name=op.f("fk_ruler_tablet_tablet_id_tablet"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ruler_id", "tablet_id", name=op.f("pk_ruler_tablet")),
    )
    op.create_table(
        "tablet_correspondent",
        sa.Column("tablet_id", sa.Integer(), nullable=False),
        sa.Column("correspondent_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["correspondent_id"],
            ["correspondent.id"],
            name=op.f("fk_tablet_correspondent_correspondent_id_correspondent"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tablet_id"],
            ["tablet.id"],
            name=op.f("fk_tablet_correspondent_tablet_id_tablet"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "tablet_id", "correspondent_id", name=op.f("pk_tablet_correspondent")
        ),
    )
    op.create_table(
        "instance_language",
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instance.id"],
            name=op.f("fk_instance_language_instance_id_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
            name=op.f("fk_instance_language_language_id_language"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "instance_id", "language_id", name=op.f("pk_instance_language")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("instance_language")
    op.drop_table("tablet_correspondent")
    op.drop_table("ruler_tablet")
    op.drop_table("instance")
    op.drop_table("tablet")
    op.drop_table("subperiod_dynasty")
    op.drop_table("reign")
    op.drop_table("city_site")
    op.drop_table("year")
    op.drop_table("sub_period")
    op.drop_table("sub_locality")
    op.drop_table("correspondent")
    op.drop_table("city")
    op.drop_table("cdp")
    op.drop_table("text_vehicle")
    op.drop_table("surface")
    with op.batch_alter_table("sign", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sign_sign_ref"))

    op.drop_table("sign")
    op.drop_table("script_type")
    op.drop_table("ruler")
    op.drop_table("period")
    with op.batch_alter_table("oracc", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oracc_sign_ref"))

    op.drop_table("oracc")
    op.drop_table("non_ruler_corresp")
    op.drop_table("method")
    op.drop_table("medium")
    op.drop_table("locality")
    op.drop_table("line")
    op.drop_table("language")
    op.drop_table("iteration")
    op.drop_table("genre")
    op.drop_table("function")
    op.drop_table("eponym")
    op.drop_table("dynasty")
    with op.batch_alter_table("description", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_description_sign_ref"))

    op.drop_table("description")
    op.drop_table("column")
    with op.batch_alter_table("cdli", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cdli_sign_ref"))

    op.drop_table("cdli")
    op.drop_table("author")
    # ### end Alembic commands ###
