"""Add CDP Sign ref table and relationship to Sign

Revision ID: 195d22b61896
Revises: 377cde07880f
Create Date: 2013-05-21 11:58:12.079385

"""

# revision identifiers, used by Alembic.
revision = '195d22b61896'
down_revision = '377cde07880f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sign_ref', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.add_column(u'sign', sa.Column('cdp_id', sa.Integer(), nullable=False))
    op.drop_column(u'sign', u'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'sign', sa.Column(u'name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column(u'sign', 'cdp_id')
    op.drop_table('cdp')
    ### end Alembic commands ###
