"""Add JJT notes to Instance

Revision ID: 1a3861bf3a05
Revises: 499765559c01
Create Date: 2014-08-21 14:05:49.163818

"""

# revision identifiers, used by Alembic.
revision = '1a3861bf3a05'
down_revision = '499765559c01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('jjt_notes', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'jjt_notes')
    ### end Alembic commands ###
