"""Add CDLI Archaic table and Sign reln

Revision ID: 1bb7ffca76ba
Revises: 42be37d009e9
Create Date: 2013-05-21 16:26:29.778306

"""

# revision identifiers, used by Alembic.
revision = '1bb7ffca76ba'
down_revision = '42be37d009e9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sign_ref', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.add_column(u'sign', sa.Column('cdli_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_cdli_sign",
        "sign",
        "cdli",
        ["cdli_id"],
        ["id"])
    op.drop_column(u'sign', u'CDLI_archaic')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'sign', sa.Column(u'CDLI_archaic', mysql.VARCHAR(length=50), nullable=True))
    op.drop_table('cdli')
    op.drop_constraint("fk_cdli_sign", "sign")
    ### end Alembic commands ###
