"""Add update and deletion cascades to CDP

Revision ID: 25b06dd4bab6
Revises: 376e994c8e0a
Create Date: 2014-08-15 16:28:05.478583

"""

# revision identifiers, used by Alembic.
revision = '25b06dd4bab6'
down_revision = '376e994c8e0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ix_sign_cdp", "cdp", type_="foreignkey")
    op.create_foreign_key(
        "fk_sign_cdp",
        "cdp",
        "sign",
        ["sign_id"],
        ["id"],
        onupdate="CASCADE", ondelete="CASCADE")

    op.drop_constraint("fk_cdli_sign", "cdp", type_="foreignkey")
    op.create_foreign_key(
        "fk_cdli_cdp",
        "cdp",
        "cdli",
        ["cdli_id"],
        ["id"],
        onupdate="CASCADE", ondelete="CASCADE")

    op.drop_constraint("fk_oracc_sign", "cdp", type_="foreignkey")
    op.create_foreign_key(
        "fk_oracc_cdp",
        "cdp",
        "oracc",
        ["oracc_id"],
        ["id"],
        onupdate="CASCADE", ondelete="CASCADE")

    op.drop_constraint("fk_description_sign", "cdp", type_="foreignkey")
    op.create_foreign_key(
        "fk_description_cdp",
        "cdp",
        "description",
        ["description_id"],
        ["id"],
        onupdate="CASCADE", ondelete="CASCADE")


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_sign_cdp", "cdp", type_="foreignkey")
    op.create_foreign_key(
        "ix_sign_cdp",
        "cdp",
        "sign",
        ["sign_id"],
        ["id"])

    op.drop_constraint("fk_cdli_cdp", "cdp", type_="foreignkey")
    op.create_foreign_key(
        "fk_cdli_sign",
        "cdp",
        "cdli",
        ["cdli_id"],
        ["id"])

    op.drop_constraint("fk_oracc_cdp", "cdp", type_="foreignkey")
    op.create_foreign_key(
        "fk_oracc_sign",
        "cdp",
        "oracc",
        ["oracc_id"],
        ["id"])

    op.drop_constraint("fk_description_cdp", "cdp", type_="foreignkey")
    op.create_foreign_key(
        "fk_description_sign",
        "cdp",
        "description",
        ["description_id"],
        ["id"])
    ### end Alembic commands ###
