"""Sync migrations with models and db state

Revision ID: 35a5d9f64330
Revises: None
Create Date: 2013-05-16 17:57:14.851416

"""

# revision identifiers, used by Alembic.
revision = '35a5d9f64330'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('period', u'from_date',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('period', u'to_date',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.add_column('sub_locality', sa.Column('locality_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_locality', 'locality_id')
    op.alter_column('period', u'to_date',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('period', u'from_date',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###
