"""Ensuring Sign and Cdp are up to date

Revision ID: 376e994c8e0a
Revises: 41209e2def0a
Create Date: 2014-08-15 04:26:51.017574

"""

# revision identifiers, used by Alembic.
revision = '376e994c8e0a'
down_revision = None
from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
