"""Adding sign columns

Revision ID: 377cde07880f
Revises: 35a5d9f64330
Create Date: 2013-05-20 20:51:46.049285

"""

# revision identifiers, used by Alembic.
revision = '377cde07880f'
down_revision = '35a5d9f64330'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sign', sa.Column('Ranke_BE_A_61', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('Labat', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('MesZL', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('CDLI_archaic', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('Koenig_AfO_Bei_16', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('REC', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('HA', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('Schroder_VS_15', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('description', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('UET_2', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('Fossey_pp', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('Clay_BE_A_10', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('Hinke', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('Clay_BE_A_14', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('KWU', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('form_description', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('variant_name', sa.String(length=5), nullable=True))
    op.add_column('sign', sa.Column('ELLes', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('HZL', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('Emar', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('aBZL', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('LAK', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('notes', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('oracc_sign', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('Schroeder_VS_12', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('ARM_XV', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('form_name', sa.String(length=5), nullable=True))
    op.add_column('sign', sa.Column('ZATU', sa.String(length=50), nullable=True))
    op.add_column('sign', sa.Column('RSP', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sign', 'RSP')
    op.drop_column('sign', 'ZATU')
    op.drop_column('sign', 'form_name')
    op.drop_column('sign', 'ARM_XV')
    op.drop_column('sign', 'Schroeder_VS_12')
    op.drop_column('sign', 'oracc_sign')
    op.drop_column('sign', 'notes')
    op.drop_column('sign', 'LAK')
    op.drop_column('sign', 'aBZL')
    op.drop_column('sign', 'Emar')
    op.drop_column('sign', 'HZL')
    op.drop_column('sign', 'ELLes')
    op.drop_column('sign', 'variant_name')
    op.drop_column('sign', 'form_description')
    op.drop_column('sign', 'KWU')
    op.drop_column('sign', 'Clay_BE_A_14')
    op.drop_column('sign', 'Hinke')
    op.drop_column('sign', 'Clay_BE_A_10')
    op.drop_column('sign', 'Fossey_pp')
    op.drop_column('sign', 'UET_2')
    op.drop_column('sign', 'description')
    op.drop_column('sign', 'Schroder_VS_15')
    op.drop_column('sign', 'HA')
    op.drop_column('sign', 'REC')
    op.drop_column('sign', 'Koenig_AfO_Bei_16')
    op.drop_column('sign', 'CDLI_archaic')
    op.drop_column('sign', 'MesZL')
    op.drop_column('sign', 'Labat')
    op.drop_column('sign', 'Ranke_BE_A_61')
    ### end Alembic commands ###
