"""Determining table differences

Revision ID: 41209e2def0a
Revises: b0de4bc6da1
Create Date: 2014-08-15 04:19:33.149746

"""

# revision identifiers, used by Alembic.
revision = '41209e2def0a'
down_revision = 'b0de4bc6da1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('fk_cdp_sign', table_name='cdp')
    op.drop_index('idx_name', table_name='city')
    op.drop_index('idx_name', table_name='city_site')
    op.drop_index('ix_column_number', table_name='column')
    op.create_unique_constraint(None, 'column', ['number'])
    op.create_index(op.f('ix_description_sign_ref'), 'description', ['sign_ref'], unique=True)
    op.drop_index('idx_name', table_name='eponym')
    op.drop_index('idx_name', table_name='function')
    op.drop_index('idx_name', table_name='genre')
    op.drop_index('ix_iteration_number', table_name='iteration')
    op.create_unique_constraint(None, 'iteration', ['number'])
    op.drop_index('idx_name', table_name='language')
    op.drop_index('ix_line_number', table_name='line')
    op.create_unique_constraint(None, 'line', ['number'])
    op.drop_index('idx_area', table_name='locality')
    op.drop_index('idx_name', table_name='medium')
    op.drop_index('idx_name', table_name='method')
    op.drop_index('idx_name', table_name='non_ruler_corresp')
    op.create_index(op.f('ix_oracc_sign_ref'), 'oracc', ['sign_ref'], unique=True)
    op.drop_index('idx_name', table_name='period')
    op.drop_index('ix_reign_rim_ref', table_name='reign')
    op.drop_index('idx_name', table_name='ruler')
    op.drop_index('idx_script', table_name='script_type')
    op.alter_column('sign', 'sign_ref',
               existing_type=mysql.VARCHAR(charset=u'utf8', collation=u'utf8_bin', length=150),
               nullable=False)
    op.create_index(op.f('ix_sign_sign_ref'), 'sign', ['sign_ref'], unique=True)
    op.drop_index('idx_name', table_name='sub_locality')
    op.drop_index('idx_name', table_name='sub_period')
    op.create_unique_constraint(None, 'sub_period', ['name'])
    op.drop_index('ix_surface_name', table_name='surface')
    op.create_unique_constraint(None, 'surface', ['name'])
    op.drop_index('idx_museum_number', table_name='tablet')
    op.drop_index('idx_name', table_name='text_vehicle')
    op.drop_index('idx_year', table_name='year')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_year', 'year', ['year'], unique=False)
    op.create_index('idx_name', 'text_vehicle', ['name'], unique=False)
    op.create_index('idx_museum_number', 'tablet', ['museum_number'], unique=False)
    op.drop_constraint(None, 'surface')
    op.create_index('ix_surface_name', 'surface', ['name'], unique=False)
    op.drop_constraint(None, 'sub_period')
    op.create_index('idx_name', 'sub_period', ['name'], unique=False)
    op.create_index('idx_name', 'sub_locality', ['name'], unique=False)
    op.drop_index(op.f('ix_sign_sign_ref'), table_name='sign')
    op.alter_column('sign', 'sign_ref',
               existing_type=mysql.VARCHAR(charset=u'utf8', collation=u'utf8_bin', length=150),
               nullable=True)
    op.create_index('idx_script', 'script_type', ['script'], unique=False)
    op.create_index('idx_name', 'ruler', ['name'], unique=False)
    op.create_index('ix_reign_rim_ref', 'reign', ['rim_ref'], unique=False)
    op.create_index('idx_name', 'period', ['name'], unique=False)
    op.drop_index(op.f('ix_oracc_sign_ref'), table_name='oracc')
    op.create_index('idx_name', 'non_ruler_corresp', ['name'], unique=False)
    op.create_index('idx_name', 'method', ['name'], unique=False)
    op.create_index('idx_name', 'medium', ['name'], unique=False)
    op.create_index('idx_area', 'locality', ['area'], unique=False)
    op.drop_constraint(None, 'line')
    op.create_index('ix_line_number', 'line', ['number'], unique=False)
    op.create_index('idx_name', 'language', ['name'], unique=False)
    op.drop_constraint(None, 'iteration')
    op.create_index('ix_iteration_number', 'iteration', ['number'], unique=False)
    op.create_index('idx_name', 'genre', ['name'], unique=False)
    op.create_index('idx_name', 'function', ['name'], unique=False)
    op.create_index('idx_name', 'eponym', ['name'], unique=False)
    op.drop_index(op.f('ix_description_sign_ref'), table_name='description')
    op.drop_constraint(None, 'column')
    op.create_index('ix_column_number', 'column', ['number'], unique=False)
    op.create_index('idx_name', 'city_site', ['name'], unique=False)
    op.create_index('idx_name', 'city', ['name'], unique=False)
    # op.create_index('fk_cdp_sign', 'cdp', ['sign_id'], unique=False)
    ### end Alembic commands ###
