"""Add Description and Oracc relations

Revision ID: 42be37d009e9
Revises: 34ffbf9b45d1
Create Date: 2013-05-21 13:49:57.172502

"""

# revision identifiers, used by Alembic.
revision = '42be37d009e9'
down_revision = '34ffbf9b45d1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oracc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sign_ref', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sign_ref', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.add_column(u'sign', sa.Column('description_id', sa.Integer(), nullable=False))
    op.add_column(u'sign', sa.Column('oracc_id', sa.Integer(), nullable=False))
    # Add relationships
    op.create_foreign_key(
        "fk_description_sign",
        "sign",
        "description",
        ["description_id"],
        ["id"])
    op.create_foreign_key(
        "fk_oracc_sign",
        "sign",
        "oracc",
        ["oracc_id"],
        ["id"])
    op.drop_column(u'sign', u'oracc_sign')
    op.drop_column(u'sign', u'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'sign', sa.Column(u'description', mysql.VARCHAR(length=50), nullable=True))
    op.add_column(u'sign', sa.Column(u'oracc_sign', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column(u'sign', 'oracc_id')
    op.drop_column(u'sign', 'description_id')
    op.drop_table('description')
    op.drop_table('oracc')
    # Drop relationships
    op.drop_constraint("fk_description_sign", "sign")
    op.drop_constraint("fk_oracc_sign", "sign")

    ### end Alembic commands ###
