"""Fix CDP constraint and index names

Revision ID: 54903f3b1315
Revises: 25b06dd4bab6
Create Date: 2014-08-15 18:49:37.558810

"""

# revision identifiers, used by Alembic.
revision = '54903f3b1315'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint("fk_sign_cdp", "cdp", type_="foreignkey")
    op.drop_index('ix_cdp_sign', table_name='cdp')

    op.drop_constraint("fk_cdli_cdp", "cdp", type_="foreignkey")
    op.drop_index('fk_cdli_sign', table_name='cdp')

    op.drop_constraint("fk_oracc_cdp", "cdp", type_="foreignkey")
    op.drop_index('fk_oracc_sign', table_name='cdp')

    op.drop_constraint("fk_description_cdp", "cdp", type_="foreignkey")
    op.drop_index('fk_description_sign', table_name='cdp')

    # now recreate them
    op.create_foreign_key(
    "fk_sign_cdp",
    "cdp",
    "sign",
    ["sign_id"],
    ["id"],
    onupdate="CASCADE", ondelete="CASCADE")

    op.create_foreign_key(
    "fk_cdli_cdp",
    "cdp",
    "cdli",
    ["cdli_id"],
    ["id"],
    onupdate="CASCADE", ondelete="CASCADE")

    op.create_foreign_key(
    "fk_oracc_cdp",
    "cdp",
    "oracc",
    ["oracc_id"],
    ["id"],
    onupdate="CASCADE", ondelete="CASCADE")

    op.create_foreign_key(
    "fk_description_cdp",
    "cdp",
    "description",
    ["description_id"],
    ["id"],
    onupdate="CASCADE", ondelete="CASCADE")
    ### end Alembic commands ###


def downgrade():
    # nope!
